### ISSUE TITLE
Request for Access to Research Data

### ISSUE THREAD

**Issue by aaaaaaaaaayong** [ding-lab/PanCan_snATAC_publication#1]
Dear Doctors,

I hope this message finds you well. My name is Chen Xiaoyong, and I am a graduate student at Sun Yat-sen University in China. I recently had the opportunity to read your remarkable article titled "Epigenetic regulation during cancer transitions across 11 tumor types," which was published in the journal "Nature." I was thoroughly impressed by the quality of your scientific research.

I am very interested in utilizing your dataset for conducting some analysis. However, I have encountered difficulties in obtaining the complete dataset from the GEO database. Unfortunately, I am unable to access the data in dbGaP as well. Therefore, I kindly request if it would be possible to provide me with the dataset in an alternative format, such as an rds file. Your assistance in this matter would be greatly appreciated.

Thank you for taking the time to read my message, and I wish you continued success in your research endeavors.

Sincerely,
Chen Xiaoyong
Sun Yat-sen University

**Comment by nvterekhanova** [comment]
Hello,

The data also can be accessed via HTAN DCC portal https://data.humantumoratlas.org/, under HTAN WUSTL Atlas. The portal provides various levels of the data. HTAN DCC and dbGaP are official forums to obtain the data.
